version: "3"
services:
  # postgres:
  #   image: "postgres:latest"
  postgres:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - BIND_ADDR=:5000
      - LOG_LEVEL=debug
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=postgres
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5050:80"
  #   restart: always
