version: "3"
services:
  #  postgres:
  #   image: "postgres:latest"
  postgres:
    # image: "postgres:latest"
    build: ./postgres-db
    ports:
      - 7557:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    build: ./migrator
    links:
      - postgres
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - BIND_ADDR=:5000
      - LOG_LEVEL=debug
volumes:
  data:
    external: true
networks:
  new:

# psql -h localhost -p 7557 -U postgres postgres

# docker run -v /home/nikita/mine/docker/docker-go-api/server/migrations:/migrations --network host migrate/migrate -path=/migrations -database "postgresql://postgres:docker@localhost:7557/postgres?sslmode=disable" up

# from container
# docker run --network host migrator -path=/migrations -database "postgresql://postgres:docker@localhost:7557/postgres?sslmode=disable" up
